### ISSUE TITLE
Dokcerizing frontend

### ISSUE THREAD

**Issue by mclub4** [Alpha-e-Um/Frontend#16]
## Feature Description

프론트엔드를 Docker 컨테이너화합니다

## Detailed Tasks

- [ ] Frontend Dockerfile 작성
- [ ] DockerHub에 업로드

## Reference Materials (Optional)
![image](https://github.com/Alpha-e-Um/Frontend/assets/55117706/2460a448-23b0-4b21-abff-8eb29cf88fab)

위 사진처럼 작동할 예정

**Comment by sukjuhong** [comment]
뭐라고 나오는지 자세히 알려주시면 좋겠습니다

**Comment by sukjuhong** [comment]
근데 사실 저희가 원하는 정확한 방식은 build를 통해 nginx가 들어오는 요청을 해당 정적 파일로 들어가는게 맞을겁니다

**Comment by mclub4** [comment]
dokcer run -p 3000:3000 react:1.0 이런식으로 포트 옵션 줘서 덕분에 해결했슴돠. expose는 컨테이너끼리 통신할때 포트이기 때문이군요. nginx는 추후 설정해서 올려두도록 하겠습니다.
