### ISSUE TITLE
AWS 배포 및 CI/CD 적용

### ISSUE THREAD

**Issue by mclub4** [Alpha-e-Um/Frontend#17]
## Feature Description

Dockerize 후, AWS EC2 인스턴스에 프론트 배포

## Detailed Tasks

- [x] Frontend를 AWS EC2 인스턴스에 배포
- [x] Nginx 적용을 통한 리버스 프록시 서버 적용
- [x] GitAction을 통한 CI/CD 적용

## Reference Materials (Optional)
![image](https://github.com/Alpha-e-Um/Frontend/assets/55117706/7c6d4f9e-98f7-4524-b4c5-b87c60e439b1)

위 그림처럼 작동할 예정입니다.

**Comment by sukjuhong** [comment]
캡스톤에서 겪었던 문제인데 google oauth2 client 만들때 redirect-uri가 public ip로는 설정이 불가능해서 .nip.io를 추가하셔야합니다~

![image](https://github.com/Alpha-e-Um/Frontend/assets/102505374/1b89ad29-e28a-434b-967c-1fe749ad97b9)

**Comment by mclub4** [comment]
@sukjuhong 저희가 이제 public ip가 아니라 e-um.site 도메인으로 바뀌었는데, 이러면 크게 상관 없는거죠?
